# params.yaml ─ central place for every tunable knob
# You can add / rename keys freely as long as you reference
# them with ${params:…} in dvc.yaml or read them in your code.

########################################################################
# ─────── Phase-2 · Data Collection ────────────────────────────────────
########################################################################
collect:
  # CLI flags passed straight through to omni_cli.py
  # Example calls shown; comment / extend as needed.
  args: >
    file data/raw/users.csv
    --redact-pii
    --save
  # If you crawl an API or DB, keep the secrets OUT of Git
  # and feed them via env-vars or your CI’s secret store.
  # (omni_cli.py reads os.environ["PG_DSN"] etc.)

########################################################################
# ─────── Phase-3 · Data Preparation ───────────────────────────────────
########################################################################
prepare:
  # flags piped into ml_pipeline.prepare
  args: >-
    --knn                     # fancy imputer
    --outlier iso             # Isolation Forest
    --scaler robust           # RobustScaler
    --balance smote           # oversample minority

########################################################################
# ─────── Phase-4½ · Feature Selection – optional thresholds ───────────
########################################################################
feature_select:
  nzv_threshold: 1e-5 # near-zero-variance filter
  corr_threshold: 0.95 # numeric corr pruning
  mi_quantile: 0.10 # bottom 10 % MI / F-score dropped

########################################################################
# ─────── Phase-5 · Feature Engineering ────────────────────────────────
########################################################################
feature:
  args: >-
    --numeric_scaler robust
    --numeric_power yeo
    --log_cols revenue
    --cat_encoding hash
    --rare_threshold 0.01
    --text_vectorizer tfidf
    --text_cols review
    --polynomial_degree 2

########################################################################
# ─────── Phase-5½ · Split & Baseline ──────────────────────────────────
########################################################################
split:
  seed: 42 # deterministic reproducibility

########################################################################
# ─────── Cross-cutting  ───────────────────────────────────────────────
########################################################################
target: is_churn # single source of truth – all stages read this
```yaml
# params.yaml

prep:
  knn: false
  outlier: "iqr"      # choices: iqr, zscore, iso
  scaler: "standard"  # choices: standard, robust, yeo
  balance: "none"     # choices: none, smote, nearmiss
  target: "is_churn"

eda:
  mode: "all"
  target: "is_churn"
  profile: true

features:
  numeric_scaler: "robust"
  numeric_power: "yeo"
  log_cols: ["revenue"]
  quantile_bins: { "age": 4 }
  polynomial_degree: 2
  rare_threshold: 0.01
  cat_encoding: "target"
  text_vectorizer: "tfidf"
  text_cols: ["review"]
  datetime_cols: ["last_login"]
  cyclical_cols: { "hour": 24 }
  date_delta_cols: { "signup_date": "2023-01-01" }
  aggregations: { "customer_id": ["amount_mean", "amount_sum"] }
  drop_nzv: true
  corr_threshold: 0.95
  mi_quantile: 0.10
  target: "is_churn"

split_baseline:
  seed: 42
  stratify: true
  oversample: false
  target: "is_churn"
```
